### ISSUE TITLE
Introduce FBTests to build a test suite

### ISSUE THREAD

**Issue by dhruvaray** [dhruvaray/spa-eye#1]

**Comment by jdkanani** [comment]
I have added boilerplate code for FBTest with commit 336c50e2c11f97e29970ec5ed144a398611898d7

How to run all fbtests?
1.  Create new `dev` (here, name is irrelevant) firefox [profile](http://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) if you have not created yet.
2. Install latest(1.12+ Recommended) [Firebug](https://getfirebug.com/)
3. Install latest [FBTest](https://getfirebug.com/releases/fbtest/)
4. Start local http server to serve test files for FBTest:

```
node build.js server <PORT>
```

It will start server at `localhost:PORT` (default port is 8888).
1. Run all fbtest cases:

```
node build.js test <PROFILE> <PORT>
```

It will run all fbtests at `localhost:PORT` with profile PROFILE (default port is 8888 and profile is 'dev').

For more details:

```
node build.js help
```
