### ISSUE TITLE
Not working from RequireJS

### ISSUE THREAD

**Issue by un1ko85** [dhruvaray/spa-eye#10]
![screen shot 2013-09-27 at 5 04 17 pm](https://f.cloud.github.com/assets/3129672/1226296/ceeb9562-277d-11e3-9cc5-6b9e576a04b7.png)

**Comment by dhruvaray** [comment]
Can you specify the version # of Backbone Eye you are using? You can pick it up from the menu as shown in the screenshot below. I just tried Backbone Eye v0.1.0-rc5  with the Backbone + Require.js todo mvc site (http://todomvc.com/dependency-examples/backbone_require/) and it seems to work fine. See below.

![bug10](https://f.cloud.github.com/assets/2075506/1226865/6a8f1e94-2788-11e3-8e47-8d0ee2022228.png)

You have a couple of options
1. Please check if you have the latest version of Backbone Eye.
2. I see from your screenshot, that you have a couple of Firebug plug-ins installed. To isolate the problem, can you create a fresh firefox profile (via firefox -p) and see if the problem yet persists?
3. Lastly, if you have a public URL, I can take a look.

**Comment by dhruvaray** [comment]
I see your script panel is also disabled. You need to enable that to make Backbone Eye work.  I think that should do the trick. Can you enable it and let me know?

**Comment by un1ko85** [comment]
enable script, work fine, thank you!!!

**Comment by dhruvaray** [comment]
Update : In Backbone-Eye v1.1, this happens automatically.
