### ISSUE TITLE
Enabling Backbone Eye makes the Enter and Up/Down keys stop working in console

### ISSUE THREAD

**Issue by EvHaus** [dhruvaray/spa-eye#12]
When I enable the Backbone Eye extension I can no longer press Enter, Up or Down keys in the multi-line console window in Firebug. It's as if the extension is simply eating those events.

**Comment by jdkanani** [comment]
I could not reproducible this problem with latest version of backbone-eye. Can you please try with latest version?

**Comment by EvHaus** [comment]
Still happening. Using Backbone Eye 0.1.1, Firebug 1.12.5, Firefox 28.0a2

**Comment by dhruvaray** [comment]
I am unable to repro with the combination you specify. Can you try it with a fresh firefox profile? (firefox -p from the command line)

**Comment by EvHaus** [comment]
Still the same issue with a fresh profile and no other addons installed. Exact steps to reproduce:
- Run firefox -p (Im using FirefoxAurora v28.0)
- Create new profile
- Launch using new profile
- Install Firebug from Addons
- Install Backbone Eye from Addons
- Open Firebug and click on the Console tab
- Click on the arrow in the bottom right corner of Firebug to open console in multi-line mode
- Attempt to type some text. Note that pressing Enter doesn't work anymore. However, Ctrl + Enter still works. But up and down keys don't work either.

When Backbone Eye is disabled - the issue goes away.

Maybe it's a issue in Firefox Aurora only? Did you try that?

**Comment by jdkanani** [comment]
I have added fix with this [commit](https://github.com/dhruvaray/spa-eye/commit/f9b74d9d598d747e232a391c8fb7388c33c352ed). Try with edge version and let me know how it goes.

How to build: https://github.com/dhruvaray/spa-eye/wiki/Generate-the-XPI-file

**Comment by EvHaus** [comment]
Looks like that fixed it.
