### ISSUE TITLE
Errors in Eye Logs

### ISSUE THREAD

**Issue by philfreo** [dhruvaray/spa-eye#3]
Just reporting some errors:

![screen shot 2013-08-20 at 9 25 13 am](https://f.cloud.github.com/assets/97612/994949/9fffe5fa-09b4-11e3-846e-e0815d26f8ea.png)
![screen shot 2013-08-20 at 9 25 29 am](https://f.cloud.github.com/assets/97612/994950/a3367d1a-09b4-11e3-826f-601f5a904948.png)
![screen shot 2013-08-20 at 9 25 36 am](https://f.cloud.github.com/assets/97612/994952/a611f366-09b4-11e3-971f-fd6a927f54f2.png)

Overall it is picking up models, collections, and views. Not picking up any of my view templates (using Handlebars).

**Comment by dhruvaray** [comment]
Thanks @philfreo 

The two errors you see are already fixed on the HEAD. You can build the latest as explained in the README. It's just a simple ant command to generate the xpi.

In v0.1.0, we are supporting only the underscore template engine. (with templateSettings changes if specified). Will add support for other templating engines in upcoming releases.

**Comment by philfreo** [comment]
I started using underscore templates a little (via Backbone-Forms) and then my entire page stopped loading. Turns out everything works fine once I disable Backbone Eye. It was causing this error:

![screen shot 2013-08-20 at 9 22 57 pm](https://f.cloud.github.com/assets/97612/999000/e268bbf6-0a18-11e3-99df-eceff43c9ece.png)

**Comment by dhruvaray** [comment]
I'll take a look. Is this app on a public URL by any chance?

**Comment by philfreo** [comment]
not with the changes I'm referring to

**Comment by jdkanani** [comment]
Thanks @philfreo for pointing this out.

We are narrowing down the problem, and it seems we missed to handle the template settings. I've included some fix for it. You can build latest and continue with your application.

I have tested Backbone-Form with this [demo app](http://mindbleach.com/demos/backbone_forms/simple/).

**Comment by dhruvaray** [comment]
@philfreo : Would appreciate it greatly if you take the time to check out your temporary website (using _ templates) with the rc1 [release](https://github.com/dhruvaray/spa-eye/releases/tag/v0.1.0-rc1)

**Comment by dhruvaray** [comment]
I'm going to close this for now... If you yet find the issue, kindly re-open.
