### ISSUE TITLE
spa-eye blocks 'add' events

### ISSUE THREAD

**Issue by itsnotvalid** [dhruvaray/spa-eye#4]
Hello, I tried this with Backbone.js 1.0.0 and I have a function call attached to listen 'add' event for a model, which the function is to create and append some view to a bootstrap tab.

However after activating spa-eye, it simply stops append the views to the dom.

Here is the code which runs to append the newly created views to dom (and some views seems to be visible in spa-eye)

```
function(question) {

        // generate tab's ids
        var timestamp = new Date().getTime();
        this.id = 'tab' + timestamp;
        this.navTabId = 'nav-tab'+ timestamp;
        this.paneId = 'nav-pane'+ timestamp;

        var view, headerView;
        headerView = new HeaderView({quizView: this, paneId: this.paneId, collection: this.questionSet, model:question, id:this.navTabId});

        // find the correct view by type
        if (question instanceof Xxx) {
            view = new XxxView({model: question, id:this.paneId, headerView: headerView});
        }
// ... more if's //

        // append into respective locations

        this.tab.append(headerView.render().$el);
        this.pane.append(view.render().$el);

        // trigger show on the tab root div as bootstrap would be confused by
        // our markups
        headerView.$el.find('a').tab('show');
}
```

which only the headerView was visible in spa-eye. Whichever XxxView were created they were not visible and not appended like they never existed.

Thanks.

**Comment by jdkanani** [comment]
Thanks @itsnotvalid 

I have fixed some underscore template related issues recently. Can you please take latest version of spa-eye and check with your application? You can find [build](https://github.com/dhruvaray/spa-eye#want-to-build-the-latest) related docs in README. 

Meanwhile I will try to reproduce this issue with your snippet.

**Comment by jdkanani** [comment]
Hi @itsnotvalid 

We just released `v0.1.0-rc1`. You can download it from [here](https://github.com/dhruvaray/spa-eye/releases/tag/v0.1.0-rc1). Please let us know if this issue is reproducible with rc1 release.

**Comment by jdkanani** [comment]
I have added small test case to test template render in view with commit 871ac0112447b2751ed1e5c10344928b76e9e0b3.
You can simply view test html page by starting http node server `node build.js server`  and accessing [this url](http://localhost:8888/test/view/template/test_template.html).

**Comment by dhruvaray** [comment]
I am closing this for now. Please re-open if you see this with v0.1.0-rc1
