### ISSUE TITLE
Not available for Firefox 18.0

### ISSUE THREAD

**Issue by hegdeashwin** [dhruvaray/spa-eye#9]
While installation its showing me Not available for Firefox 18.0 message.
Do you have any work around? Thanks

**Comment by dhruvaray** [comment]
Nope... As specified in our documentation, it only works with FF23+ and Firebug 1.12+

**Comment by hegdeashwin** [comment]
Hum.....ok. Thanks

**Comment by wwwboy** [comment]
I have FF25 but after instalation - there is no tab or anything with Backbone eye (

**Comment by dhruvaray** [comment]
A couple of things you can do to help me resolve it for you:
- Can you drop in a screenshot to this bug?
- Backbone Eye depends on Firebug. So I am assuming you have Firebug. Which version of Firebug do you use?
- Start Firefox on a fresh profile. (In the command line, do firefox - p somename. Then install the latest Firebug and BB-Eye from the Mozilla store

**Comment by wwwboy** [comment]
Thanks, I havnt mention Firebug!
Everithing works!
